DROP TABLE IF EXISTS public.livros;

CREATE TABLE IF NOT EXISTS public.livros
(
    "ID" SERIAL NOT NULL,
    "Titulo" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Codigo" character varying(13)  COLLATE pg_catalog."default" NOT NULL,
    "Descricao" text COLLATE pg_catalog."default",
    "Editora" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Numero de paginas" smallint NOT NULL,
    "Preco" numeric(12,2) NOT NULL,
    "Formato" character varying(255) COLLATE pg_catalog."default" NOT NULL,
    "Quantidade" integer NOT NULL,
    "Categoria" character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT "Livro_pkey" PRIMARY KEY ("ID", "Codigo")
)

TABLESPACE pg_default;

INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Pequeno manual antirracista', '9788535932874', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Pólen', 136, 17.90, 'Capa comum', FLOOR(random()*(100))+1, 'Sociedade');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Mulheres que correm com os lobos', '9788532529787', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Rocco', 576, 34.90, 'Capa dura', FLOOR(random()*(100))+1, 'Psicologia');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('1984', '9788582851197', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Penguin-Companhia', 392, 13.83, 'Capa comum', FLOOR(random()*(100))+1, 'Romance');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('O poder do hábito: Por que fazemos o que fazemos na vida e nos negócios', '9788539004119', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Objetiva', 408, 46.90, 'Capa comum', FLOOR(random()*(100))+1, 'Economia');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('O Morro dos Ventos Uivantes', 'B097FBT3QL', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Principis', 368, 0, 'Ebook', -1, 'Romance');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('O milagre da manhã: O segredo para transformar sua vida (antes das 8 horas)', '9788576849940', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'BestSeller', 196, 24.98, 'Capa comum', FLOOR(random()*(100))+1, 'Autoajuda');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Mais esperto que o Diabo: O mistério revelado da liberdade e do sucesso', '9788568014004', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Citadel', 208, 24.90, 'Capa comum', FLOOR(random()*(100))+1, 'Educação');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('A revolução dos bichos: Um conto de fadas', '9788535909555', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Companhia das Letras', 152, 14.90, 'Capa comum', FLOOR(random()*(100))+1, 'Ficção');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Racismo Estrutural (Feminismos Plurais)', 'B07TTJR74W', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Editora Jandaíra', 232, 0, 'Ebook', -1, 'Política');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('A coragem de ser imperfeito', '9788543104331', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Editora Sextante', 208, 29.90, 'Capa comum', FLOOR(random()*(100))+1, 'Autoajuda');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Mindset: A nova psicologia do sucesso', '9788547000240', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Objetiva', 312, 27.90, 'Capa comum', FLOOR(random()*(100))+1, 'Psicologia');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('O conto da aia', '9788532520661', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Rocco', 368, 20.50, 'Capa comum', FLOOR(random()*(100))+1, 'Ficção');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Do Mil ao Milhão. Sem Cortar o Cafezinho', '9788595083271', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'HarperCollins', 192, 17.60, 'Capa comum', FLOOR(random()*(100))+1, 'Economia');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('21 lições para o século 21', 'B07BFGS9Y5', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Companhia das Letras', 355, 29.90, 'Ebook', -1, 'História');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Essencialismo: A disciplinada busca por menos', '9786555641431', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Editora Sextante', 288, 37.89, 'Capa dura', FLOOR(random()*(100))+1, 'Economia');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Os segredos da mente milionária', '9788575422397', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Editora Sextante', 176, 29.99, 'Capa comum', FLOOR(random()*(100))+1, 'Economia');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Escravidão – Volume 1: Do primeiro leilão de cativos em Portugal até a morte de Zumbi dos Palmares', 'B07VN7DVM1', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Globo Livros', 593, 29.90, 'Capa comum', -1, 'Sociedade');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Sapiens - Uma Breve História da Humanidade', '9788525432186', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'L&PM', 464, 59.90, 'Capa comum', FLOOR(random()*(100))+1, 'História');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('O homem mais rico da Babilônia', '9788595081536', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'HarperCollins', 160, 15.90, 'Capa comum', FLOOR(random()*(100))+1, 'Arte');
INSERT INTO livros ("Titulo", "Codigo", "Descricao", "Editora", "Numero de paginas", "Preco", "Formato", "Quantidade", "Categoria") VALUES ('Harry Potter e a Pedra Filosofal', '9788532511010', 'Mussum Ipsum, cacilds vidis litro abertis. Mauris nec dolor in eros commodo tempor.', 'Pottermore Publishing', 309, 0, 'Ebook', -1, 'Infanto juvenil');
